app:
  name: "thirftbam"
  http:
    host: 152.136.135.225
    post: :8888

log:
  log_level: debug
  encoding: console           # json or console
  log_file_name: "./logs/server.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true

data:
  db:
    user:
#      dsn: root:KingYen.2004@tcp(127.0.0.1:3306)/newbam?charset=utf8mb4&parseTime=True&loc=Local
      dsn: root:ndwmd1230@tcp(1.94.38.238:3306)/newbam?charset=utf8mb4&parseTime=True&loc=Local

  redis:
    addr: 114.116.241.37:6379
    password: bam595.
    db: 0
    read_timeout: 0.2s
    write_timeout: 0.2s

rocketmq:
  nameSrv: 118.178.229.137:9876
  log: "./logs/rmq.log"
  consumers:
    - group: "slow_queue_consumer"
      topic: "Slow_Update"
    - group: "fast_queue_consumer"
      topic: "Fast_Update"