app:
  name: "thirftbam"
  http:
    addr: 127.0.0.1:8888

log:
  log_level: debug
  encoding: console           # json or console
  log_file_name: "./logs/server.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true