// Code generated by hertz generator.

package main

import (
	"context"
	"flag"
	"fmt"
	"github.com/ByteBam/thirftbam/cmd/wire"
	"github.com/ByteBam/thirftbam/util/config"
	"github.com/ByteBam/thirftbam/util/log"
	"go.uber.org/zap"
)

func main() {
	var envConf = flag.String("conf", "biz/config/config.yaml", "config file path")
	flag.Parse()
	conf := config.NewConfig(*envConf)

	logger := log.NewLog(conf)

	app, cleanup, err := wire.NewWire(conf, logger)
	defer cleanup()
	if err != nil {
		panic(err)
	}
	logger.Info("server start", zap.String("addr", fmt.Sprintf("http://%s", conf.GetString("app.http.addr"))))
	logger.Info("docs addr", zap.String("addr", fmt.Sprintf("http://%s/swagger/index.html", conf.GetString("app.http.host"))))
	if err = app.Run(context.Background()); err != nil {
		panic(err)
	}
}
