// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBranch = "branch"

// Branch mapped from table <branch>
type Branch struct {
	ID            string    `gorm:"column:id;type:char(19);not null" json:"id"`
	StoreID       string    `gorm:"column:store_id;type:char(19);not null;comment:仓库id" json:"store_id"`                                 // 仓库id
	BranchName    string    `gorm:"column:branch_name;type:char(32);not null;comment:分支名" json:"branch_name"`                            // 分支名
	GitUpdateTime time.Time `gorm:"column:git_update_time;type:datetime;comment:git最后修改时间" json:"git_update_time"`                       // git最后修改时间
	InterfaceNum  int32     `gorm:"column:interface_num;type:int;comment:接口数量" json:"interface_num"`                                     // 接口数量
	Status        int32     `gorm:"column:status;type:int;not null;comment:分支状态" json:"status"`                                          // 分支状态
	UpdateTime    time.Time `gorm:"column:update_time;type:datetime;default:CURRENT_TIMESTAMP;comment:修改时间" json:"update_time"`          // 修改时间
	CreateTime    time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
}

// TableName Branch's table name
func (*Branch) TableName() string {
	return TableNameBranch
}
