// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInterfaceInfo = "interface_info"

// InterfaceInfo mapped from table <interface_info>
type InterfaceInfo struct {
	ID            string    `gorm:"column:id;type:char(19);primaryKey" json:"id"`
	InterfaceName string    `gorm:"column:interface_name;type:varchar(255);comment:接口名称" json:"interface_name"`                 // 接口名称
	URL           string    `gorm:"column:url;type:varchar(1024);comment:接口地址" json:"url"`                                      // 接口地址
	Parameter     string    `gorm:"column:parameter;type:text;comment:参数" json:"parameter"`                                     // 参数
	Method        string    `gorm:"column:method;type:varchar(24);not null;comment:请求方式" json:"method"`                         // 请求方式
	IsDeleted     int32     `gorm:"column:is_deleted;type:tinyint;comment:删除状态  1 true  0 false" json:"is_deleted"`             // 删除状态  1 true  0 false
	CreateTime    time.Time `gorm:"column:create_time;type:datetime;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime    time.Time `gorm:"column:update_time;type:datetime;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	ModuleID      string    `gorm:"column:module_id;type:char(19);not null;comment:模块id" json:"module_id"`                      // 模块id
	Response      string    `gorm:"column:response;type:text;comment:响应参数" json:"response"`                                     // 响应参数
}

// TableName InterfaceInfo's table name
func (*InterfaceInfo) TableName() string {
	return TableNameInterfaceInfo
}
