// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		Branch:          newBranch(db, opts...),
		InterfaceInfo:   newInterfaceInfo(db, opts...),
		LinkedThirdUser: newLinkedThirdUser(db, opts...),
		ModuleInfo:      newModuleInfo(db, opts...),
		Store:           newStore(db, opts...),
		User:            newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Branch          branch
	InterfaceInfo   interfaceInfo
	LinkedThirdUser linkedThirdUser
	ModuleInfo      moduleInfo
	Store           store
	User            user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Branch:          q.Branch.clone(db),
		InterfaceInfo:   q.InterfaceInfo.clone(db),
		LinkedThirdUser: q.LinkedThirdUser.clone(db),
		ModuleInfo:      q.ModuleInfo.clone(db),
		Store:           q.Store.clone(db),
		User:            q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Branch:          q.Branch.replaceDB(db),
		InterfaceInfo:   q.InterfaceInfo.replaceDB(db),
		LinkedThirdUser: q.LinkedThirdUser.replaceDB(db),
		ModuleInfo:      q.ModuleInfo.replaceDB(db),
		Store:           q.Store.replaceDB(db),
		User:            q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Branch          IBranchDo
	InterfaceInfo   IInterfaceInfoDo
	LinkedThirdUser ILinkedThirdUserDo
	ModuleInfo      IModuleInfoDo
	Store           IStoreDo
	User            IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Branch:          q.Branch.WithContext(ctx),
		InterfaceInfo:   q.InterfaceInfo.WithContext(ctx),
		LinkedThirdUser: q.LinkedThirdUser.WithContext(ctx),
		ModuleInfo:      q.ModuleInfo.WithContext(ctx),
		Store:           q.Store.WithContext(ctx),
		User:            q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
